include $(TOPDIR)/rules.mk

PKG_NAME:=gluon-fastd-ipv4overv6-workaround
PKG_VERSION:=1
PKG_RELEASE:=1

PKG_BUILD_DIR := $(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/gluon-fastd-ipv4overv6-workaround
  SECTION:=gluon
  CATEGORY:=Gluon
  TITLE:=Workaround for IPv4 over IPv6 or DS-Lite MTU problems
  DEPENDS:=+gluon-cron +luci-lib-json +iw
endef

define Package/gluon-fastd-ipv4overv6-workaround/description
	Gluon community wifi mesh firmware framework: workaround module for MTU issues caused by DS-Lite
endef

define Build/Prepare
endef

define Build/Configure
endef

define Build/Compile
endef

define Package/gluon-channel-survey/install
	$(CP) ./files/* $(1)/
endef

$(eval $(call BuildPackage,gluon-channel-survey))